# Generated by Django 5.0.10 on 2026-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccount_ciudad_useraccount_codpostal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='provider',
            field=models.CharField(blank=True, default='manual', max_length=30, null=True),
        ),
    ]
